"""Pluggable daily basket execution planner."""

from .analytics import cumulative_side_completion
from .config import (
    TradePlannerConfig,
    default_earnings_aware_config,
    default_rebalance_aware_config,
)
from .constraints import (
    ConstraintDiagnostics,
    ConstraintPlugin,
    DailyGrossNotionalLimit,
    DailyNetNotionalLimit,
    DirectionConstraint,
    FactorExposureLimit,
    HardCompletionConstraint,
    MinCompletionByDate,
    OptimizationState,
    ParticipationCapacityConstraint,
    ZeroTargetConstraint,
    VariableDiagnostics,
    default_constraints,
    get_constraint_diagnostics,
    get_variable_diagnostics,
    with_diagnostics,
    with_variable_diagnostics,
)
from .context import PlannerContext, days_to_next_event
from .costs import CompositeCostModel, EarningsLinearPenalty, LinearBpsCost, QuadraticParticipationImpact
from .data import (
    FactorRiskData,
    PlannerDataProvider,
    align_date_symbol_field,
    align_factor_covariance,
    align_factor_exposure,
    align_specific_variance,
    assemble_context,
    build_context_from_provider,
    build_market_panel_from_provider,
    build_planner_dates,
    normalize_orders,
)
from .diagnostics import diagnose_infeasible_problem, diagnose_problem, format_diagnosis, format_infeasibility_diagnosis
from .mosek_diagnostics import DiagnosticMOSEK
from .participation import (
    AdaptiveAnnouncementParticipation,
    AnnouncementParticipationCurve,
    AnnouncementParticipationModifier,
    LogisticEarningsParticipation,
    ParticipationCapModel,
    PiecewiseEarningsParticipation,
    announcement_participation_rates,
)
from .planner import TradePlanner, TradePlannerResult
from .risk import (
    BarraFactorRiskModel,
    ExponentialEarningsRiskOverlay,
    RiskModel,
    SpecificRiskOverlay,
    StaticCovarianceRiskModel,
)
from .types import InfeasiblePlanError

__all__ = [
    "AdaptiveAnnouncementParticipation",
    "BarraFactorRiskModel",
    "AnnouncementParticipationCurve",
    "AnnouncementParticipationModifier",
    "CompositeCostModel",
    "ConstraintDiagnostics",
    "ConstraintPlugin",
    "DiagnosticMOSEK",
    "DailyGrossNotionalLimit",
    "DailyNetNotionalLimit",
    "DirectionConstraint",
    "EarningsLinearPenalty",
    "ExponentialEarningsRiskOverlay",
    "FactorRiskData",
    "FactorExposureLimit",
    "HardCompletionConstraint",
    "InfeasiblePlanError",
    "LinearBpsCost",
    "LogisticEarningsParticipation",
    "MinCompletionByDate",
    "OptimizationState",
    "ParticipationCapacityConstraint",
    "ParticipationCapModel",
    "PiecewiseEarningsParticipation",
    "PlannerContext",
    "PlannerDataProvider",
    "QuadraticParticipationImpact",
    "RiskModel",
    "SpecificRiskOverlay",
    "StaticCovarianceRiskModel",
    "TradePlanner",
    "TradePlannerConfig",
    "TradePlannerResult",
    "VariableDiagnostics",
    "ZeroTargetConstraint",
    "align_date_symbol_field",
    "align_factor_covariance",
    "align_factor_exposure",
    "align_specific_variance",
    "assemble_context",
    "build_market_panel_from_provider",
    "build_planner_dates",
    "build_context_from_provider",
    "cumulative_side_completion",
    "days_to_next_event",
    "default_constraints",
    "default_earnings_aware_config",
    "default_rebalance_aware_config",
    "diagnose_infeasible_problem",
    "diagnose_problem",
    "format_diagnosis",
    "format_infeasibility_diagnosis",
    "get_constraint_diagnostics",
    "get_variable_diagnostics",
    "normalize_orders",
    "with_diagnostics",
    "with_variable_diagnostics",
    "announcement_participation_rates",
]
