"""Pluggable daily basket execution planner."""

from .alpha import (
    ConfidenceAdjustedExpectedReturnAlphaModel,
    ExpectedReturnAlphaModel,
    InventoryAlphaModel,
)
from .analytics import cumulative_side_completion
from .calibration import (
    DEFAULT_MAX_OPTIMIZATION_SCENARIOS,
    DEFAULT_RISK_PREFERENCES,
    CalibratedRebalancePlan,
    RebalanceEconomicMetrics,
    RebalanceFrontier,
    RebalanceRiskMeasure,
    RiskAversion,
    RiskPreference,
    build_rebalance_frontier,
    calibrate_rebalance_plan,
    evaluate_rebalance_schedule,
    infer_execution_cost_matrices,
    infer_execution_costs,
)
from .config import (
    TradePlannerConfig,
    default_earnings_aware_config,
    default_rebalance_aware_config,
)
from .constraints import (
    ConstraintDiagnostics,
    ConstraintPlugin,
    DailyGrossNotionalLimit,
    DailyNetNotionalLimit,
    DirectionConstraint,
    FactorExposureLimit,
    HardCompletionConstraint,
    MinCompletionByDate,
    OptimizationState,
    ParticipationCapacityConstraint,
    ZeroTargetConstraint,
    VariableDiagnostics,
    default_constraints,
    get_constraint_diagnostics,
    get_variable_diagnostics,
    with_diagnostics,
    with_variable_diagnostics,
)
from .context import PlannerContext, days_to_next_event
from .costs import (
    CompositeCostModel,
    EarningsLinearPenalty,
    LinearBpsCost,
    QuadraticParticipationImpact,
    TCALinearBpsCost,
    TCAQuadraticParticipationImpact,
)
from .data import (
    FactorRiskData,
    PlannerDataProvider,
    align_date_symbol_field,
    align_factor_covariance,
    align_factor_exposure,
    align_return_scenarios,
    align_scenario_weights,
    align_specific_variance,
    assemble_context,
    build_context_from_provider,
    build_market_panel_from_provider,
    build_planner_dates,
    normalize_orders,
)
from .diagnostics import diagnose_infeasible_problem, diagnose_problem, format_diagnosis, format_infeasibility_diagnosis
from .downside import (
    InventoryPathRiskModel,
    ScenarioCVaRRiskModel,
    TailSecondMomentPathRiskModel,
    TailStressPathRiskModel,
    centered_return_scenarios,
    reduce_return_scenarios,
    tail_return_scenarios,
    tail_stress_return_path,
    weighted_loss_var_cvar,
)
from .mosek_diagnostics import DiagnosticMOSEK
from .historical import HistoricalReplayBundle, load_historical_replay_bundle
from .alpha_decay import (
    DEFAULT_MIN_TRAINING_EVENTS,
    RIDGE_MULTIPLIERS as ALPHA_DECAY_RIDGE_MULTIPLIERS,
    AlphaDecayWalkForward,
    ConditionalAlphaDecayModel,
    calibrate_alpha_decay_walk_forward,
    summarize_alpha_decay_predictions,
)
from .participation import (
    AdaptiveAnnouncementParticipation,
    AnnouncementParticipationCurve,
    AnnouncementParticipationModifier,
    LogisticEarningsParticipation,
    ParticipationCapModel,
    PiecewiseEarningsParticipation,
    announcement_participation_rates,
)
from .planner import TradePlanner, TradePlannerResult
from .policy_calibration import (
    FALLBACK_AGGRESSIVENESS,
    PROFILE_CONFIDENCE,
    AutomaticRiskProfileCalibration,
    InvestmentPolicyCoefficients,
    build_monotone_policy_ladder,
    calibrate_risk_profiles_walk_forward,
    summarize_risk_profile_selections,
)
from .risk import (
    BarraFactorRiskModel,
    ExponentialEarningsRiskOverlay,
    RiskModel,
    SpecificRiskOverlay,
    StaticCovarianceRiskModel,
)
from .types import InfeasiblePlanError
from .walkforward import (
    PointInTimeRebalanceEvent,
    RealizedRebalanceMetrics,
    WalkForwardReplay,
    evaluate_realized_rebalance_schedule,
    replay_rebalance_events,
    validate_point_in_time_event,
)

__all__ = [
    "AdaptiveAnnouncementParticipation",
    "ALPHA_DECAY_RIDGE_MULTIPLIERS",
    "AlphaDecayWalkForward",
    "AutomaticRiskProfileCalibration",
    "BarraFactorRiskModel",
    "AnnouncementParticipationCurve",
    "AnnouncementParticipationModifier",
    "CompositeCostModel",
    "CalibratedRebalancePlan",
    "ConfidenceAdjustedExpectedReturnAlphaModel",
    "ConditionalAlphaDecayModel",
    "ConstraintDiagnostics",
    "ConstraintPlugin",
    "DiagnosticMOSEK",
    "DailyGrossNotionalLimit",
    "DailyNetNotionalLimit",
    "DEFAULT_MAX_OPTIMIZATION_SCENARIOS",
    "DEFAULT_MIN_TRAINING_EVENTS",
    "DEFAULT_RISK_PREFERENCES",
    "DirectionConstraint",
    "EarningsLinearPenalty",
    "ExpectedReturnAlphaModel",
    "ExponentialEarningsRiskOverlay",
    "FactorRiskData",
    "FactorExposureLimit",
    "FALLBACK_AGGRESSIVENESS",
    "HardCompletionConstraint",
    "HistoricalReplayBundle",
    "InfeasiblePlanError",
    "InventoryAlphaModel",
    "InvestmentPolicyCoefficients",
    "InventoryPathRiskModel",
    "LinearBpsCost",
    "LogisticEarningsParticipation",
    "MinCompletionByDate",
    "OptimizationState",
    "ParticipationCapacityConstraint",
    "ParticipationCapModel",
    "PiecewiseEarningsParticipation",
    "PROFILE_CONFIDENCE",
    "PlannerContext",
    "PlannerDataProvider",
    "PointInTimeRebalanceEvent",
    "QuadraticParticipationImpact",
    "RebalanceEconomicMetrics",
    "RebalanceFrontier",
    "RebalanceRiskMeasure",
    "RealizedRebalanceMetrics",
    "RiskAversion",
    "RiskModel",
    "RiskPreference",
    "ScenarioCVaRRiskModel",
    "TailSecondMomentPathRiskModel",
    "TailStressPathRiskModel",
    "SpecificRiskOverlay",
    "StaticCovarianceRiskModel",
    "TCALinearBpsCost",
    "TCAQuadraticParticipationImpact",
    "TradePlanner",
    "TradePlannerConfig",
    "TradePlannerResult",
    "VariableDiagnostics",
    "WalkForwardReplay",
    "ZeroTargetConstraint",
    "align_date_symbol_field",
    "align_factor_covariance",
    "align_factor_exposure",
    "align_return_scenarios",
    "align_scenario_weights",
    "align_specific_variance",
    "assemble_context",
    "build_market_panel_from_provider",
    "build_monotone_policy_ladder",
    "build_planner_dates",
    "build_context_from_provider",
    "build_rebalance_frontier",
    "calibrate_alpha_decay_walk_forward",
    "calibrate_risk_profiles_walk_forward",
    "calibrate_rebalance_plan",
    "centered_return_scenarios",
    "reduce_return_scenarios",
    "tail_return_scenarios",
    "tail_stress_return_path",
    "cumulative_side_completion",
    "days_to_next_event",
    "default_constraints",
    "default_earnings_aware_config",
    "default_rebalance_aware_config",
    "diagnose_infeasible_problem",
    "diagnose_problem",
    "evaluate_rebalance_schedule",
    "evaluate_realized_rebalance_schedule",
    "format_diagnosis",
    "format_infeasibility_diagnosis",
    "get_constraint_diagnostics",
    "get_variable_diagnostics",
    "infer_execution_costs",
    "infer_execution_cost_matrices",
    "load_historical_replay_bundle",
    "normalize_orders",
    "replay_rebalance_events",
    "summarize_alpha_decay_predictions",
    "summarize_risk_profile_selections",
    "with_diagnostics",
    "with_variable_diagnostics",
    "weighted_loss_var_cvar",
    "validate_point_in_time_event",
    "announcement_participation_rates",
]
